### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by sbueringer** [hedgedoc/hedgedoc#1182]
**Which part of the project should be enhanced?**
Github authentication

**Is your enhancement request related to a problem? Please describe.**
I wanted to use hedgedoc with Github Enterprise but there is no configuration option for the GitHub URL.

**Describe the solution you'd like**
Would be nice to be able to configure the Github URL. Not sure how much effort this is. codimd seems to support it ([implementation](https://github.com/hackmdio/codimd/blob/e00eaa82a98423b9eeb904b9c9fc8fc939f9f6e6/lib/auth/github/index.js)).

**Describe alternatives you've considered**

**Additional context**

**Comment by DerMolly** [comment]
Hey @sbueringer,

you should be able to use the OAuth2 login provider (see https://docs.github.com/en/enterprise-server@3.0/developers/apps/authorizing-oauth-apps) to use HedgeDoc with Github Enterprise right now.

Maybe we want to add a new config option for a Github Enterprise URL in 2.0?

**Comment by mrdrogdrog** [comment]
I don't see a need for an extra option. HedgeDoc 2 will also support oauth

**Comment by sbueringer** [comment]
Okay got, it thank you. Feel free to close if you don't want to add an extra option. 

I think it's nice and intuitive for users if you can configure a separate URL in the Github authentication, but
of course if it also works with the more generic OAuth option that's enough to get it working.

**Comment by prologic** [comment]
I would like to see a "Github EE" specific option as well, or a URL in the "Github" configuration. I mean Gitlab has this, why not Github? This is just convenience at this point, as it is, I'm actually trying to figure out the right env vars to pass to hedgedoc here to get it to with against out internal Github EE instance (_if anyone has an example, that's be very helpful!_)

**Comment by ErikMichelson** [comment]
Customizable GitHub authentication servers are on our note when implementing this feature in HedgeDoc 2. However due to a limited amount of time, we won't add this feature in HedgeDoc 1.x.

I do not have an GitHub EE instance to test, however I just verified the following config part with GitHub.com:

```
      - CMD_OAUTH2_USER_PROFILE_URL=https://api.github.com/user
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=login
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_TOKEN_URL=https://github.com/login/oauth/access_token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://github.com/login/oauth/authorize
      - CMD_OAUTH2_CLIENT_ID=xxxxxxxxxxxxx
      - CMD_OAUTH2_CLIENT_SECRET=xxxxxxxxxxxxxxx
      - CMD_OAUTH2_PROVIDERNAME=GitHub

```

**Comment by prologic** [comment]
Farrrrk soryr about the wrong eomji 😂 mis-taped on my iPhone 🤦‍♂️

**Comment by prologic** [comment]
Kind of also wondering if any of y'all have tried to tie HedgeDoc's Auth into Gitea?

I've tried the following config so far with no success:

```
      - CMD_OAUTH2_TOKEN_URL=https://git.mydomain.com/login/oauth/access_token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://git.mydomain.com/login/oauth/userinfo
      - CMD_OAUTH2_CLIENT_ID=<redacted>
      - CMD_OAUTH2_CLIENT_SECRET=<redacted>
      - CMD_OAUTH2_PROVIDERNAME=Gitea
```

I get an error like (which likely comes from Gitea):

```
no valid authorization
```

**Comment by prologic** [comment]
Oh! 🤦‍♂️ I _think_ I'm using the OpenID endpoing by mistake 😂

**Comment by prologic** [comment]
Looks like I've run into a bug or misconfigured, the Auth worked, but HedgeDoc blew up :/

Pasting here as I'm not sure what's going on yet...

```
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    | TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at new NodeError (node:internal/errors:371:5)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at validateString (node:internal/validators:120:11)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at Url.parse (node:url:169:3)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at Object.urlParse [as parse] (node:url:156:13)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at exports.OAuth2._request (/hedgedoc/node_modules/oauth/lib/oauth2.js:72:22)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at exports.OAuth2.get (/hedgedoc/node_modules/oauth/lib/oauth2.js:227:8)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at OAuth2CustomStrategy.userProfile (/hedgedoc/lib/web/auth/oauth2/index.js:93:16)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at loadIt (/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:389:17)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at OAuth2CustomStrategy.OAuth2Strategy._loadUserProfile (/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:404:25)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at /hedgedoc/node_modules/passport-oauth2/lib/strategy.js:180:16
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at /hedgedoc/node_modules/oauth/lib/oauth2.js:209:7
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at passBackControl (/hedgedoc/node_modules/oauth/lib/oauth2.js:134:9)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at IncomingMessage.<anonymous> (/hedgedoc/node_modules/oauth/lib/oauth2.js:157:7)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at IncomingMessage.emit (node:events:538:35)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at endReadableNT (node:internal/streams/readable:1345:12)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    | 2022-05-06T23:31:45.701Z error: 	An uncaught exception has occured.
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    | 2022-05-06T23:31:45.701Z error: 	The "url" argument must be of type string. Received undefined
hedgedoc_hedgedoc.1.4hnmjkn7yk24@dm6.mydomain.com    | 2022-05-06T23:31:45.701Z error: 	Process will exit now.
hedgedoc_hedgedoc.1.24h397hlp80t@dm6.mydomain.com    | 2022-05-06T23:32:17.147Z info: 	127.0.0.1 - - [06/May/2022:23:32:17 +0000] "GET /status HTTP/1.1" 200 267 "-" "hedgedoc-container-healthcheck/1.0"
```

**Comment by prologic** [comment]
I'm not actually sure how to satisfy the OAuth2 requirements between HedgeDoc and Gitea, I supplied a few extra (were missing) config parameters:

```
      - CMD_OAUTH2_USER_PROFILE_URL=https://git.mydomain.com/login/oauth/userinfo
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=login
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
```
(these are likely wrong somehow)

But still get an error on the HedgeDoc backend:

```
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    | 2022-05-06T23:44:35.563Z info: 	10.0.0.109 - - [06/May/2022:23:44:35 +0000] "GET /auth/oauth2 HTTP/1.1" 302 0 "https://docs.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    | TypeError: Cannot read properties of undefined (reading 'toString')
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at OAuth2CustomStrategy.callback [as _verify] (/hedgedoc/lib/web/auth/utils.js:10:29)
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at /hedgedoc/node_modules/passport-oauth2/lib/strategy.js:205:24
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at /hedgedoc/lib/web/auth/oauth2/index.js:110:5
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at passBackControl (/hedgedoc/node_modules/oauth/lib/oauth2.js:134:9)
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at IncomingMessage.<anonymous> (/hedgedoc/node_modules/oauth/lib/oauth2.js:157:7)
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at IncomingMessage.emit (node:events:538:35)
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at endReadableNT (node:internal/streams/readable:1345:12)
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
hedgedoc_hedgedoc.1.rc7r4jbtv4a6@dm6.mydomain.com    | 2022-05-06T23:44:35.837Z info: 	10.0.0.109 - - [06/May/2022:23:44:35 +0000] "GET /auth/oauth2/callback?code=y5sk7jaXWeV98VACncdkjgwlyYCfmVyGSZ7jfoAQfuGG&state=qak4Hp44OcT3XiPPfdHzg9W8 HTTP/1.1" 500 148 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
```

**Comment by prologic** [comment]
Success! 🥳

<img width="233" alt="Screen Shot 2022-05-07 at 09 53 40" src="https://user-images.githubusercontent.com/1290234/167228880-659cd1e6-19be-4f78-8144-57433256ef0f.png">

The _correct_ config for HedgeDoc <-> Gitea Auth in the end is/was:

```
      - CMD_OAUTH2_USER_PROFILE_URL=https://git.mydomain.com/login/oauth/userinfo
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=preferred_username
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_TOKEN_URL=https://git.mydomain.com/login/oauth/access_token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://git.mydomain.com/login/oauth/authorize
      - CMD_OAUTH2_CLIENT_ID=<redacted>
      - CMD_OAUTH2_CLIENT_SECRET=<redacted>
```

The important config items are/were:

```
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=preferred_username
```

Make note of the `name` and `preferred_username` attrs.

Where would you guys like me to document this?

I only have one problem left, where shall I discuss/talk about this? That is I'm logged in, but I have no way to associate my old (Email) login with my OAuth2 login (despite the fact the usernames match). So I have no access to my old document. I'd have to migrate them manually. It would be nice if I could tie the two logins together as one?

**Comment by ErikMichelson** [comment]
> Where would you guys like me to document this?

The best place would probably be the HedgeDoc community forum at https://community.hedgedoc.org
There is a thread where people do share their configs and recommendations [here](https://community.hedgedoc.org/t/how-do-you-use-codimd/18).

>  I'm logged in, but I have no way to associate my old (Email) login with my OAuth2 login ... It would be nice if I could tie the two logins together as one?

Sorry, this is currently not possible in HedgeDoc 1 without fiddling manually in the database. However we have such a feature (linking of accounts to multiple login identities) on our roadmap for HedgeDoc 2.

**Comment by ErikMichelson** [comment]
I'm going to lock this issue as this discussion is out of context for this issue. Feel free to open a new issue or post on our community forum for follow-up problems/ideas/etc.
