### ISSUE TITLE
Webpack is not found

### ISSUE THREAD

**Issue by titulebolide** [hedgedoc/hedgedoc#1272]
**Description**
When updating from 1.8.0 to 1.8.2, I receive the error `/bin/sh: 1: webpack: not found` while building hedgedoc, even though I ran bin/setup beforehand

This error is fixed by running `yarn` and thus installing all the dependencies. Is bin/setup not installing/refreshing the dependencies?

**To Reproduce**
```
git pull
git checkout 1.8.2
bin/setup
yarn run build
```

**Expected behavior**
It is expected to run fine

**Logs**
```
$ ~ yarn run build
yarn run v1.22.4
$ webpack --config webpack.prod.js --progress
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Your Setup (please complete the following information):**
 - Host OS: Raspberry Pi OS Buster (Debian 10)
 - NodeJS version : 12.20.1
 - HedgeDoc version (Click "Version info" in the footer)
     - server 1.8.2
     - client 1.8.2

Thanks!

**Comment by titulebolide** [comment]
Closing this issue as I did not read the updated installation doc.

Nonetheless it is surprising to have to run yarn install after bin/setup
Maybe bin/setup could run `yarn install` instead of `yarn install --production` ?

**Comment by mrdrogdrog** [comment]
This is done on purpose. The tar ball (which we recommend) and the docker image don't need the dependencies for building the frontend because the prebundled frontend is already included.

**Comment by titulebolide** [comment]
Okay, that makes sense

Sorry for bothering!

**Comment by mrdrogdrog** [comment]
You're not bothering at all! It was a legit problem. Maybe this issue will help other people with the same problem.

**Comment by meepmeep** [comment]
Sorry to re-open this issue, but I tried to upgrade to 1.9.1 and I still got a webpack error even with the `yarn install` before the `build `(using the git or the tarball) :

```
meepmeep:~/hedgedoc$ ./bin/setup && yarn install && yarn build
Copying config files...
Installing packages...
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.63s.
If you want to build the frontend yourself, you need to run 'yarn install' before 'yarn build' to install the devDependencies for the build process.

Edit the following config file to setup HedgeDoc server and client.
Read more info at https://docs.hedgedoc.org/configuration/

* config.json           -- HedgeDoc config
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.60s.
yarn run v1.22.10
$ webpack --config webpack.prod.js --progress
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
meepmeep:~/hedgedoc$ nodejs --version
v14.18.2
meepmeep:~/hedgedoc$ yarn --version
1.22.10
```

With the tarball and `bin/setup && NODE_ENV=production yarn start`  :  

```
meepmeep:~/hedgedoc$ NODE_ENV=production yarn start
yarn run v1.22.10
$ node app.js
fatal: not a git repository (or any of the parent directories): .git
2021-12-03T09:29:01.082Z warn:  config.json contains wrong version (use 'v4' if gitlab version > 11, 'v3' otherwise. Default to 'v4') for gitlab api; it should be 'v3' or 'v4'. Defaulting to v4
2021-12-03T09:29:01.084Z warn:  Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2021-12-03T09:29:01.318Z error:         uncaughtException: Cannot find module 'babel-runtime/core-js/json/stringify'
Require stack:
- /home/lufi/hedgedoc/node_modules/mattermost/lib/client.js
- /home/lufi/hedgedoc/lib/web/auth/mattermost/index.js
- /home/lufi/hedgedoc/lib/web/auth/index.js
- /home/lufi/hedgedoc/app.js
Error: Cannot find module 'babel-runtime/core-js/json/stringify'
Require stack:
- /home/lufi/hedgedoc/node_modules/mattermost/lib/client.js
- /home/lufi/hedgedoc/lib/web/auth/mattermost/index.js
- /home/lufi/hedgedoc/lib/web/auth/index.js
- /home/lufi/hedgedoc/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:232)
    at t (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:115)
    at Object.<anonymous> (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:459)
    at t (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:115)
    at Object.<anonymous> (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:2:11385)
    at t (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:115)
    at /home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:197
    at Object.<anonymous> (/home/lufi/hedgedoc/node_modules/mattermost/lib/client.js:1:206)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/lufi/hedgedoc/lib/web/auth/mattermost/index.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
^C
```

**Comment by davidmehren** [comment]
@meepmeep Regarding building the frontend: This looks like `yarn install` still did not install the development dependencies. Do you have `NODE_ENV=production` in your environment? You can force yarn to install dev dependencies with `yarn install --production=false`.

Regarding the second error: This seems like a problem with the mattermost login. Do you use that?

**Comment by meepmeep** [comment]
`yarn install --production=false` did the trick.
I was using `NODE_END=production` only for `yarn start`, I updated my doc ;)
