### ISSUE TITLE
504 with oauth2 login

### ISSUE THREAD

**Issue by TheMrPhantom** [hedgedoc/hedgedoc#1433]
**Description**
I get an 504 error after my oauth2 redirect on the url `/auth/oauth2/callback?state=xxx&code=xxx
`

**Logs**
```
InternalOAuthError: Failed to obtain access token
    at OAuth2CustomStrategy.OAuth2Strategy._createOAuthError (/opt/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:408:17)
    at /opt/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /opt/hedgedoc/node_modules/oauth/lib/oauth2.js:191:18
     at ClientRequest.<anonymous> (/opt/hedgedoc/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:314:20)
     at TLSSocket.socketErrorListener (_http_client.js:427:9)
     at TLSSocket.emit (events.js:314:20)
     at emitErrorNT (internal/streams/destroy.js:92:8)
     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by remyd1** [comment]
I know this issue is a bit old, but indeed, there is a solution on the community forum [here](https://community.hedgedoc.org/t/internaloautherror-failed-to-obtain-access-token-with-nextcloud/526/2).

Debugging with curl allowed me to fix that issue (my CA certificate was not included in my nginx configuration on the keycloak server).
