### ISSUE TITLE
Cannot find module 'babel-runtime/core-js/json/stringify'

### ISSUE THREAD

**Issue by devthejo** [hedgedoc/hedgedoc#1452]
**Description**
running in k8s, when enabling mattermost oauth 2, get ""Cannot find module 'babel-runtime/core-js/json/stringify' error.
**To Reproduce**
```sh
helm -n $NS upgrade --install $RELEASE nicholaswilde/hedgedoc -f - <<EOF
env:
  TZ: Europe/Paris
  # DEBUG: "true"
  CMD_DOMAIN: $HEDGEDOC_SUBDOMAIN.$MY_DOMAIN
  CMD_PROTOCOL_USESSL: "true"
  CMD_ALLOW_EMAIL_REGISTER: "false"
  CMD_ALLOW_ANONYMOUS: "false"
  CMD_ALLOW_FREEURL: "true"
  CMD_REQUIRE_FREEURL_AUTHENTICATION: "true"
  CMD_IMAGE_UPLOAD_TYPE: filesystem
  CMD_SESSION_SECRET: $SESSION_SECRET
  CMD_MATTERMOST_BASEURL: https://$MATTERMOST_SUBDOMAIN.$MY_DOMAIN
  CMD_MATTERMOST_CLIENTID: $MATTERMOST_CLIENTID
  CMD_MATTERMOST_CLIENTSECRET: $MATTERMOST_CLIENTSECRET
  # CMD_OAUTH2_PROVIDERNAME: "MATTERMOST_SUBDOMAIN.$MY_DOMAIN"
  # CMD_OAUTH2_BASEURL: https://$MATTERMOST_SUBDOMAIN.$MY_DOMAIN
  # CMD_OAUTH2_USER_PROFILE_URL: https://$MATTERMOST_SUBDOMAIN.$MY_DOMAIN/api/v4/users/me
  # CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR: id
  # CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR: username
  # CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR: email
  # CMD_OAUTH2_TOKEN_URL: https://$MATTERMOST_SUBDOMAIN.$MY_DOMAIN/oauth/access_token
  # CMD_OAUTH2_AUTHORIZATION_URL: https://$MATTERMOST_SUBDOMAIN.$MY_DOMAIN/oauth/authorize
  # CMD_OAUTH2_CLIENT_ID: $MATTERMOST_CLIENTID
  # CMD_OAUTH2_CLIENT_SECRET: $MATTERMOST_CLIENTSECRET

persistence:
  config:
    enabled: true

mariadb:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: $HEDGEDOC_SUBDOMAIN.$MY_DOMAIN
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hedgedoc
            port:
              number: 3000
  tls:
    - secretName: tls-rancher-ingress
      hosts:
        - $HEDGEDOC_SUBDOMAIN.$MY_DOMAIN
EOF
```

**Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing...

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 10-adduser: executing...

usermod: no changes

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    911

User gid:    911

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing...

[cont-init.d] 30-config: exited 0.

[cont-init.d] 90-custom-folders: executing...

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-scripts: executing...

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

2021-07-17T23:21:52.353Z error: 	uncaughtException: Cannot find module 'babel-runtime/core-js/json/stringify'

Require stack:

- /opt/hedgedoc/node_modules/mattermost/lib/client.js

- /opt/hedgedoc/lib/web/auth/mattermost/index.js

- /opt/hedgedoc/lib/web/auth/index.js

- /opt/hedgedoc/app.js

Error: Cannot find module 'babel-runtime/core-js/json/stringify'

Require stack:

- /opt/hedgedoc/node_modules/mattermost/lib/client.js

- /opt/hedgedoc/lib/web/auth/mattermost/index.js

- /opt/hedgedoc/lib/web/auth/index.js

- /opt/hedgedoc/app.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/opt/hedgedoc/node_modules/mattermost/lib/client.js:1:232)

    at t (/opt/hedgedoc/node_modules/mattermost/lib/client.js:1:115)

    at Object.<anonymous> (/opt/hedgedoc/node_modules/mattermost/lib/client.js:1:459)

    at t (/opt/hedgedoc/node_modules/mattermost/lib/client.js:1:115)

    at Object.<anonymous> (/opt/hedgedoc/node_modules/mattermost/lib/client.js:2:11385)

    at t (/opt/hedgedoc/node_modules/mattermost/lib/client.js:1:115)

    at /opt/hedgedoc/node_modules/mattermost/lib/client.js:1:197

    at Object.<anonymous> (/opt/hedgedoc/node_modules/mattermost/lib/client.js:1:206)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/opt/hedgedoc/lib/web/auth/mattermost/index.js:5:20)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.
```

**Config**

**Your Setup (please complete the following information):**
 - Host OS: RKE2 (Kubernetes) on Debian 10
 - HedgeDoc version
     - server 1.8.2 (ghcr.io/linuxserver/hedgedoc:version-1.8.2)

**Additional context**
I'm able to run it without CMD_MATTERMOST_* env vars defined, but when I try to use CMD_OAUTH2_* en vars instead to connect mattermost I get stuck with a 500 internal server error and in logs: "InternalOAuthError: Failed to obtain access token", without any others clues on what's happening (but it's maybe another uneralted error).

Thanks in advance for your help :-)

**Comment by davidmehren** [comment]
The `CMD_MATTERMOST` settings only work with Mattermost older than 5. For version 5 and up, OAuth must be used.

Did you follow https://docs.hedgedoc.org/guides/auth/mattermost-self-hosted/ for setting up OAuth?

**Comment by devthejo** [comment]
OK, got it, I'll use OAUTH.
Yes, I have configured my instance of mattermost exactly as described in this guide, provided the secret and clientid to hedgedoc, and even with debug enabled I can't get any other clues to resolve the bug. I found a similar issue on old repo (codimd) but there was no answer https://github.com/hackmdio/codimd/issues/1583 .

**Comment by davidmehren** [comment]
Please provide a full log of the error, including the stack trace.

Could you also check, if you can `curl` the URL in `CMD_OAUTH2_TOKEN_URL` from inside the HedgeDoc container?

**Comment by devthejo** [comment]
Yes of course, sorry that wasn't the original issue so I forgot to do, here is:
```
InternalOAuthError: Failed to obtain access token

    at OAuth2CustomStrategy.OAuth2Strategy._createOAuthError (/opt/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:408:17)

    at /opt/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:175:45

    at /opt/hedgedoc/node_modules/oauth/lib/oauth2.js:191:18

    at ClientRequest.<anonymous> (/opt/hedgedoc/node_modules/oauth/lib/oauth2.js:162:5)

    at ClientRequest.emit (events.js:314:20)

    at TLSSocket.socketErrorListener (_http_client.js:427:9)

    at TLSSocket.emit (events.js:314:20)

    at emitErrorNT (internal/streams/destroy.js:92:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

2021-07-18T08:20:24.811Z info: 	10.0.0.22 - - [18/Jul/2021:08:20:24 +0000] "GET /auth/oauth2/callback?code=x48cb8nhh7nn3ebp4yjfsj1s8e7y8dqmp1xf8fig3kchnbsqaa9h&state=Gu4aCJR7Zm2KyhOY87NgW9VY HTTP/1.1" 500 148 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0"
```
I'll try to curl right now

**Comment by devthejo** [comment]
I get an SSL certificate error, and it's logic, I use a self signed generated certificate generated by mkcert (my dev cluster is local and don't rely on public dns), is there any way to disable ssl secure verification ?

**Comment by davidmehren** [comment]
You can set the `NODE_TLS_REJECT_UNAUTHORIZED` [environment variable](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value), which obviously is *very* unsafe.

A better way is to add you CA cert to the trusted CAs via the [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) environment variable.

**Comment by devthejo** [comment]
OK, awesome, many thanks for your help !
