### ISSUE TITLE
Heroku build error

### ISSUE THREAD

**Issue by Cnets-io** [hedgedoc/hedgedoc#1761]
### Description

Build error when deploying with default button on homepage

### Steps to reproduce

1. https://docs.hedgedoc.org/setup/heroku/ click on Deploy button
2. Provide name 
3. Click deploy app at bottom
4. Build failed 

### Expected behaviour

Build finishes, deployed app

### Logs

```shell
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_PRODUCTION=false
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  >=12
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >=12...
       Downloading and installing node 17.0.0...
       Using default npm version: 8.1.0
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.17)
       Installed yarn 1.22.17
       
-----> Prebuild
       Running heroku-prebuild (yarn)
       yarn run v1.22.17
       $ bin/heroku
       Done in 0.12s.
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.17
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       warning " > connect-session-sequelize@7.1.2" has incorrect peer dependency "sequelize@>= 6.1.0".
       [4/4] Building fresh packages...
       Done in 65.78s.
       
-----> Build
       Running build (yarn)
       yarn run v1.22.17
       $ webpack --config webpack.prod.js --progress
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active 
<s> [webpack.Progress] 10% building 0/0 modules 0 active 
<s> [webpack.Progress] 10% building 0/1 modules 1 active multi expose-loader?exposes[]=$&exposes[]=jQuery!jquery velocity-animate imports-loader?imports=default|jquery|$!jquery-mousewheel bootstrap
<s> [webpack.Progress] 10% building 1/1 modules 0 active 
<s> [webpack.Progress] 10% building 1/1 modules 0 active 
<s> [webpack.Progress] 10% building 1/2 modules 1 active multi babel-polyfill /tmp/build_a3f3e3ba/public/js/cover.js
<s> [webpack.Progress] 10% building 2/2 modules 0 active 
<s> [webpack.Progress] 10% building 2/2 modules 0 active 
<s> [webpack.Progress] 10% building 2/3 modules 1 active multi /tmp/build_a3f3e3ba/node_modules/bootstrap/dist/css/bootstrap.min.css /tmp/build_a3f3e3ba/node_modules/fork-awesome/css/fork-awesome.min.css /tmp/build_a3f3e3ba/public/css/bootstrap-social.css /tmp/build_a3f3e3ba/node_modules/select2/select2.css /tmp/build_a3f3e3ba/node_modules/select2/select2-bootstrap.css
<s> [webpack.Progress] 10% building 3/3 modules 0 active 
<s> [webpack.Progress] 10% building 3/3 modules 0 active 
<s> [webpack.Progress] 10% building 3/4 modules 1 active multi babel-polyfill bootstrap-validator expose-loader?exposes=select2!select2 expose-loader?exposes=moment!moment /tmp/build_a3f3e3ba/public/js/cover.js
<s> [webpack.Progress] 10% building 4/4 modules 0 active 
<s> [webpack.Progress] 10% building 4/4 modules 0 active 
<s> [webpack.Progress] 10% building 4/5 modules 1 active multi babel-polyfill expose-loader?exposes=LZString!lz-string flowchart.js js-sequence-diagrams expose-loader?exposes=RevealMarkdown!reveal-markdown /tmp/build_a3f3e3ba/public/js/index.js
<s> [webpack.Progress] 10% building 5/5 modules 0 active 
<s> [webpack.Progress] 10% building 5/5 modules 0 active 
<s> [webpack.Progress] 10% building 5/6 modules 1 active multi /tmp/build_a3f3e3ba/public/vendor/codemirror-spell-checker/spell-checker.min.css /tmp/build_a3f3e3ba/node_modules/codemirror/lib/codemirror.css /tmp/build_a3f3e3ba/node_modules/codemirror/addon/fold/foldgutter.css /tmp/build_a3f3e3ba/node_modules/codemirror/addon/display/fullscreen.css /tmp/build_a3f3e3ba/node_modules/codemirror/addon/dialog/dialog.css /tmp/build_a3f3e3ba/node_modules/codemirror/addon/scroll/simplescrollbars.css /tmp/build_a3f3e3ba/node_modules/codemirror/addon/search/matchesonscrollbar.css /tmp/build_a3f3e3ba/node_modules/codemirror/theme/monokai.css /tmp/build_a3f3e3ba/node_modules/codemirror/theme/one-dark.css /tmp/build_a3f3e3ba/node_modules/codemirror/mode/tiddlywiki/tiddlywiki.css /tmp/build_a3f3e3ba/node_modules/codemirror/mode/mediawiki/mediawiki.css /tmp/build_a3f3e3ba/node_modules/spin.js/spin.css /tmp/build_a3f3e3ba/public/css/github-extract.css /tmp/build_a3f3e3ba/public/vendor/showup/showup.css /tmp/build_a3f3e3ba/public/css/mermaid.css /tmp/build_a3f3e3ba/public/css/markdown.css /tmp/build_a3f3e3ba/public/css/slide-preview.css
<s> [webpack.Progress] 10% building 6/6 modules 0 active 
<s> [webpack.Progress] 10% building 6/6 modules 0 active 
<s> [webpack.Progress] 10% building 6/7 modules 1 active multi /tmp/build_a3f3e3ba/node_modules/bootstrap/dist/css/bootstrap.min.css /tmp/build_a3f3e3ba/node_modules/fork-awesome/css/fork-awesome.min.css /tmp/build_a3f3e3ba/public/css/bootstrap-social.css /tmp/build_a3f3e3ba/node_modules/ionicons/css/ionicons.min.css
<s> [webpack.Progress] 10% building 7/7 modules 0 active 
<s> [webpack.Progress] 10% building 7/7 modules 0 active 
<s> [webpack.Progress] 10% building 7/8 modules 1 active multi babel-polyfill bootstrap-validator expose-loader?exposes=jsyaml!js-yaml expose-loader?exposes=moment!moment expose-loader?exposes=emojify!emojify.js expose-loader?exposes=LZString!lz-string flowchart.js js-sequence-diagrams expose-loader?exposes=io!socket.io-client expose-loader?exposes=RevealMarkdown!reveal-markdown /tmp/build_a3f3e3ba/public/js/index.js
<s> [webpack.Progress] 10% building 8/8 modules 0 active 
<s> [webpack.Progress] 10% building 8/8 modules 0 active 
<s> [webpack.Progress] 10% building 8/9 modules 1 active multi babel-polyfill flowchart.js js-sequence-diagrams expose-loader?exposes=RevealMarkdown!reveal-markdown /tmp/build_a3f3e3ba/public/js/pretty.js
<s> [webpack.Progress] 11% building 9/9 modules 0 active 
<s> [webpack.Progress] 11% building 9/9 modules 0 active 
<s> [webpack.Progress] 11% building 9/10 modules 1 active multi /tmp/build_a3f3e3ba/public/css/github-extract.css /tmp/build_a3f3e3ba/public/css/mermaid.css /tmp/build_a3f3e3ba/public/css/markdown.css /tmp/build_a3f3e3ba/public/css/slide-preview.css
<s> [webpack.Progress] 11% building 10/10 modules 0 active 
<s> [webpack.Progress] 11% building 10/10 modules 0 active 
<s> [webpack.Progress] 11% building 10/11 modules 1 active multi /tmp/build_a3f3e3ba/node_modules/bootstrap/dist/css/bootstrap.min.css /tmp/build_a3f3e3ba/node_modules/fork-awesome/css/fork-awesome.min.css /tmp/build_a3f3e3ba/node_modules/ionicons/css/ionicons.min.css
<s> [webpack.Progress] 11% building 11/11 modules 0 active 
<s> [webpack.Progress] 11% building 11/11 modules 0 active 
<s> [webpack.Progress] 11% building 11/12 modules 1 active multi babel-polyfill expose-loader?exposes=jsyaml!js-yaml expose-loader?exposes=moment!moment expose-loader?exposes=emojify!emojify.js flowchart.js js-sequence-diagrams expose-loader?exposes=RevealMarkdown!reveal-markdown /tmp/build_a3f3e3ba/public/js/pretty.js
<s> [webpack.Progress] 11% building 12/12 modules 0 active 
<s> [webpack.Progress] 11% building 12/12 modules 0 active 
<s> [webpack.Progress] 11% building 12/13 modules 1 active multi babel-polyfill bootstrap-tooltip flowchart.js js-sequence-diagrams expose-loader?exposes=RevealMarkdown!reveal-markdown /tmp/build_a3f3e3ba/public/js/slide.js
<s> [webpack.Progress] 11% building 13/13 modules 0 active 
<s> [webpack.Progress] 11% building 13/13 modules 0 active 
<s> [webpack.Progress] 11% building 13/14 modules 1 active multi /tmp/build_a3f3e3ba/public/vendor/bootstrap/tooltip.min.css /tmp/build_a3f3e3ba/public/css/github-extract.css /tmp/build_a3f3e3ba/public/css/mermaid.css /tmp/build_a3f3e3ba/public/css/markdown.css
<s> [webpack.Progress] 11% building 14/14 modules 0 active 
<s> [webpack.Progress] 11% building 14/14 modules 0 active 
<s> [webpack.Progress] 11% building 14/15 modules 1 active multi /tmp/build_a3f3e3ba/node_modules/fork-awesome/css/fork-awesome.min.css /tmp/build_a3f3e3ba/node_modules/ionicons/css/ionicons.min.css
<s> [webpack.Progress] 11% building 15/15 modules 0 active 
<s> [webpack.Progress] 11% building 15/15 modules 0 active 
<s> [webpack.Progress] 11% building 15/16 modules 1 active multi babel-polyfill expose-loader?exposes[]=$&exposes[]=jQuery!jquery velocity-animate imports-loader?imports=default|jquery|$!jquery-mousewheel bootstrap-tooltip expose-loader?exposes=jsyaml!js-yaml expose-loader?exposes=moment!moment expose-loader?exposes=emojify!emojify.js flowchart.js js-sequence-diagrams expose-loader?exposes=Reveal!reveal.js expose-loader?exposes=RevealMarkdown!reveal-markdown /tmp/build_a3f3e3ba/public/js/slide.js
<s> [webpack.Progress] 11% building 16/16 modules 0 active 
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active 
<s> [webpack.Progress] 11% building 16/17 modules 1 active /tmp/build_a3f3e3ba/public/vendor/bootstrap/tooltip.min.js
<s> [webpack.Progress] 10% building 0/1 modules 1 active /tmp/build_a3f3e3ba/public/js/htmlExport.js
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/tmp/build_a3f3e3ba/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/build_a3f3e3ba/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/build_a3f3e3ba/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/build_a3f3e3ba/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/build_a3f3e3ba/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/build_a3f3e3ba/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/build_a3f3e3ba/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/tmp/build_a3f3e3ba/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/build_a3f3e3ba/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/build_a3f3e3ba/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /tmp/build_a3f3e3ba/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v17.0.0
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

### Config

```shell
Default
```

### Your Setup

Default

### Additional context

Looks like node.js version pulled by default is latest (17) not LTS, which might cause the issue with webpack build

**Comment by mrdrogdrog** [comment]
We could fix this by either limiting the node version in package.json... or by making HedgeDoc 1 compatible with node 17.

@davidmehren
