### ISSUE TITLE
Internal Server Error reported, logs say “unexpected placeholder”

### ISSUE THREAD

**Issue by gergelypolonkai** [hedgedoc/hedgedoc#1852]
### Description

When one of our users open any HedgeDoc page (notes list, a specific note, anything), they get an Internal Server Error

### Steps to reproduce

Not sure if there are any. All other users can use the service just fine. This one user gets ISE all the time when using Chrome, but not when using Firefox.

### Expected behaviour

The pages load without an error.

### Logs

```shell
SyntaxError: /hedgedoc/public/views/hedgedoc.ejs:10
    8| <body translate="no">
    9|     <%- include('hedgedoc/header') %>
 >> 10|     <%- include('hedgedoc/body') %>
    11|     <%- include('hedgedoc/footer') %>
    12| </body>
    13|

/hedgedoc/public/views/hedgedoc/body.ejs:252
    250| <%- include('../shared/refresh-modal') %>
    251| <%- include('../shared/signin-modal') %>
 >> 252| <%- include('../shared/help-modal') %>
    253| <%- include('../shared/revision-modal') %>
    254|

/hedgedoc/public/views/shared/help-modal.ejs:20
    18|                                 <a href="https://community.hedgedoc.org" target="_blank"><i class="fa fa-users fa-fw"></i> <%= __('Join the community') %></a>
    19|                                 <br>
 >> 20|                                 <a href="https://chat.hedgedoc.org" target="_blank"><i class="fa fa-hashtag fa-fw"></i> <%= __('Meet us on %s', 'Matrix') %></a>
    21|                                 <br>
    22|                                 <a href="https://github.com/hedgedoc/hedgedoc/issues" target="_blank"><i class="fa fa-tag fa-fw"></i> <%= __('Report an issue') %></a>
    23|                                 <br>

[sprintf] unexpected placeholder
    at sprintf_parse (/hedgedoc/node_modules/sprintf-js/src/sprintf.js:202:23)
    at sprintf (/hedgedoc/node_modules/sprintf-js/src/sprintf.js:26:31)
    at vsprintf (/hedgedoc/node_modules/sprintf-js/src/sprintf.js:30:24)
    at postProcess (/hedgedoc/node_modules/i18n/i18n.js:635:13)
    at Object.i18nTranslate (/hedgedoc/node_modules/i18n/i18n.js:294:12)
    at eval ("/hedgedoc/public/views/shared/help-modal.ejs":21:26)
    at help-modal (/hedgedoc/node_modules/ejs/lib/ejs.js:692:17)
    at include (/hedgedoc/node_modules/ejs/lib/ejs.js:690:39)
    at eval ("/hedgedoc/public/views/hedgedoc/body.ejs":151:17)
    at body (/hedgedoc/node_modules/ejs/lib/ejs.js:692:17)
    at include (/hedgedoc/node_modules/ejs/lib/ejs.js:690:39)
    at eval ("/hedgedoc/public/views/hedgedoc.ejs":18:17)
    at hedgedoc (/hedgedoc/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/hedgedoc/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/hedgedoc/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/hedgedoc/node_modules/express/lib/view.js:135:8)
    at tryRender (/hedgedoc/node_modules/express/lib/application.js:640:10)
    at Function.render (/hedgedoc/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/hedgedoc/node_modules/express/lib/response.js:1012:7)
    at /hedgedoc/lib/web/note/controller.js:77:16
    at /hedgedoc/lib/web/note/util.js:30:16
    at tryCatcher (/hedgedoc/node_modules/bluebird/js/release/util.js:16:23)
2021-11-30T15:48:19.003Z info: 	176.63.10.132 - - [30/Nov/2021:15:48:19 +0000] "GET /FEST_R4TRrC9cE2m7lhOwQ HTTP/1.1" 500 148 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
```

### Your Setup

- Host OS: [e.g. Ubuntu 20.04]
- NodeJS version: [run `node --version`]
- HedgeDoc version: (Click "Releases" in the footer)

### Additional context

I just found the problem in the Hungarian translation (was `Találkozzon velünk% s`, note the wrong placement of space between percent sign and `s`.

**Comment by mrdrogdrog** [comment]
Interesting. According to https://poeditor.com/projects/po_edit?order=&filter=&per_page=20&id=175959&id_language=65&search=meet+us the string is correct. Seems like our imported json files are wrong.

**Comment by mrdrogdrog** [comment]
Ohh okay. That explains a lot :sweat_smile: 
We can't see when a string has been updated.

**Comment by mrdrogdrog** [comment]
It will be fixed in HedgeDoc with the next release. We update the language json files with every release.

**Comment by SISheogorath** [comment]
Sounds like we want to get 1.9.1 out the door rather sooner than later. It is a complete show stopper for everyone using this language.

**Comment by DerMolly** [comment]
With https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.1 this should be fixed. If you still encounter this problem feel free to reopen this issue.
