### ISSUE TITLE
Error when starting systemctl service

### ISSUE THREAD

**Issue by xeruf** [hedgedoc/hedgedoc#1926]
### Description

Hedgedoc shows an error in the log when started via systemctl on arch linux

### Steps to reproduce

- install `hedgedoc` package on Archlinux
- start with `systemctl start hedgedoc`
- view log with `journalctl -u hedgedoc`

### Expected behaviour

No errors in log

### Logs

```shell
Dec 21 14:42:07 systemd[1]: Starting Hedgedoc real-time collaborative markdown editor...
Dec 21 14:42:07 systemd[1]: Started Hedgedoc real-time collaborative markdown editor.
Dec 21 14:42:09 npm[1969582]: > HedgeDoc@1.9.2 start
Dec 21 14:42:09 npm[1969582]: > node app.js
Dec 21 14:42:09 npm[1969601]: fatal: not a git repository (or any of the parent directories): .git
Dec 21 14:42:09 npm[1969601]: 2021-12-21T14:42:09.624Z warn:         config.json contains wrong version (use 'v4'
 if gitlab version > 11, 'v3' otherwise. Default to 'v4') for gitlab api; it should be 'v3' or 'v4'. Defaulting t
o v4
Dec 21 14:42:09 npm[1969601]: 2021-12-21T14:42:09.627Z warn:         Session secret not set. Using random generat
ed one. Please set `sessionSecret` in your config.json file. All users will be logged out.
Dec 21 14:42:10 npm[1969601]: 2021-12-21T14:42:10.260Z error:         uncaughtException: Cannot find module 'babe
l-runtime/core-js/json/stringify'
Dec 21 14:42:10 npm[1969601]: Require stack:
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/node_modules/mattermost/lib/client.js
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/lib/web/auth/mattermost/index.js
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/lib/web/auth/index.js
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/app.js
Dec 21 14:42:10 npm[1969601]: Error: Cannot find module 'babel-runtime/core-js/json/stringify'
Dec 21 14:42:10 npm[1969601]: Require stack:
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/node_modules/mattermost/lib/client.js
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/lib/web/auth/mattermost/index.js
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/lib/web/auth/index.js
Dec 21 14:42:10 npm[1969601]: - /usr/share/webapps/hedgedoc/app.js
Dec 21 14:42:10 npm[1969601]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
Dec 21 14:42:10 npm[1969601]:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
Dec 21 14:42:10 npm[1969601]:     at Module.require (node:internal/modules/cjs/loader:999:19)
Dec 21 14:42:10 npm[1969601]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 21 14:42:10 npm[1969601]:     at Object.<anonymous> (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/
client.js:1:232)
Dec 21 14:42:10 npm[1969601]:     at t (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/client.js:1:115)
Dec 21 14:42:10 npm[1969601]:     at Object.<anonymous> (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/
client.js:1:459)
Dec 21 14:42:10 npm[1969601]:     at t (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/client.js:1:115)
Dec 21 14:42:10 npm[1969601]:     at Object.<anonymous> (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/
client.js:2:11385)
Dec 21 14:42:10 npm[1969601]:     at t (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/client.js:1:115)
Dec 21 14:42:10 npm[1969601]:     at /usr/share/webapps/hedgedoc/node_modules/mattermost/lib/client.js:1:197
Dec 21 14:42:10 npm[1969601]:     at Object.<anonymous> (/usr/share/webapps/hedgedoc/node_modules/mattermost/lib/
client.js:1:206)
Dec 21 14:42:10 npm[1969601]:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
Dec 21 14:42:10 npm[1969601]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
Dec 21 14:42:10 npm[1969601]:     at Module.load (node:internal/modules/cjs/loader:975:32)
Dec 21 14:42:10 npm[1969601]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Dec 21 14:42:10 npm[1969601]:     at Module.require (node:internal/modules/cjs/loader:999:19)
Dec 21 14:42:10 npm[1969601]:     at require (node:internal/modules/cjs/helpers:102:18)
Dec 21 14:42:10 npm[1969601]:     at Object.<anonymous> (/usr/share/webapps/hedgedoc/lib/web/auth/mattermost/inde
x.js:5:20)
Dec 21 14:42:10 npm[1969601]:     at Module._compile (node:internal/modules/cjs/loader:1097:14)
Dec 21 14:42:10 npm[1969601]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
Dec 21 14:42:10 npm[1969601]:     at Module.load (node:internal/modules/cjs/loader:975:32)
```

### Your Setup

- Host OS: Arch
- NodeJS version: v16.13.1
- HedgeDoc version: Latest

**Comment by davidmehren** [comment]
Do you use Mattermost auth? That is deprecated since [1.2.1](https://github.com/hedgedoc/hedgedoc/releases/tag/1.2.1).
Please include your config in the issue description.

**Comment by xeruf** [comment]
There is no config and no authentication. I only followed the exact steps listed above.

**Comment by davidmehren** [comment]
It seems Arch just ships our [example config](https://github.com/hedgedoc/hedgedoc/blob/master/config.json.example) by default. This is not a useable config. You must change the `production` section of the config in `/etc/webapps/hedgedoc/` according to your needs. For a minimal example, take a look at our [manual setup guide](https://docs.hedgedoc.org/setup/manual-setup/) and check out our [config reference](https://docs.hedgedoc.org/configuration/).
For running in production, also consult our [docs](https://docs.hedgedoc.org/guides/reverse-proxy/) about using a reverse-proxy.
