### ISSUE TITLE
GET /api/private/config results in Internal Server Error

### ISSUE THREAD

**Issue by DerMolly** [hedgedoc/hedgedoc#2150]
### Description

Internal Server Error

### Steps to reproduce

1. start the server with the following config
2. GET `http://localhost:3000/api/private/config`

### Expected behaviour

No Internal Server Error

### Logs

```shell
[HedgeDoc.ExceptionsHandler()] Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at FrontendConfigService.getIframeCommunication (/usr/src/app/frontend-config/frontend-config.service.js:141:27)
    at FrontendConfigService.getFrontendConfig (/usr/src/app/frontend-config/frontend-config.service.js:46:39)
    at ConfigController.getFrontendConfig (/usr/src/app/api/private/config/config.controller.js:27:49)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/usr/src/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
```

### Config

```shell
HD_DOMAIN=localhost
HD_MEDIA_BACKEND=filesystem
HD_MEDIA_BACKEND_FILESYSTEM_UPLOAD_PATH=uploads
HD_DATABASE_DIALECT=sqlite
HD_DATABASE_STORAGE=hedgedoc.sqlite
HD_SESSION_SECRET=foobar
HD_LOGLEVEL=debug
```

### Your Setup

This bug was found while testing the new docker image @ 9743afff19b6948c08d1ab4d394d6bae826e542b

**Comment by ErikMichelson** [comment]
Didn't we want to replace the domain config option with a URL config option anyway?
That URL option would also include ports and protocol.
