### ISSUE TITLE
Internal Server Error when Content-Type: text/markdown missing

### ISSUE THREAD

**Issue by the-lightstack** [hedgedoc/hedgedoc#2694]
### Description

When making a POST request to the `/new` endpoint without a `Content-Type: text/markdown` header, we get back a 500 status code, which should not be the case. 

### Steps to reproduce

1. Install hedge-doc via the default `docker-compose.yml`
2. Execute `curl -X POST -d "markdown header missing" http://localhost:3000/new`

The server will have an internal error.

### Expected behaviour

A `Bad Request (400)` status-code/response or `Missing Header (?)`

### Logs

```
app_1       | TypeError: body.replace is not a function
app_1       |     at exports.createFromPOST (/hedgedoc/lib/web/note/controller.js:91:15)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/route.js:144:13)
app_1       |     at textParser (/hedgedoc/node_modules/body-parser/lib/types/text.js:78:7)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/route.js:144:13)
app_1       |     at Route.dispatch (/hedgedoc/node_modules/express/lib/router/route.js:114:3)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at /hedgedoc/node_modules/express/lib/router/index.js:284:15
app_1       |     at Function.process_params (/hedgedoc/node_modules/express/lib/router/index.js:346:12)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/index.js:280:10)
app_1       |     at Function.handle (/hedgedoc/node_modules/express/lib/router/index.js:175:3)
app_1       |     at router (/hedgedoc/node_modules/express/lib/router/index.js:47:12)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at trim_prefix (/hedgedoc/node_modules/express/lib/router/index.js:328:13)
app_1       |     at /hedgedoc/node_modules/express/lib/router/index.js:286:9
app_1       |     at Function.process_params (/hedgedoc/node_modules/express/lib/router/index.js:346:12)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/index.js:280:10)
app_1       |     at /hedgedoc/node_modules/express/lib/router/index.js:646:15
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/index.js:265:14)
app_1       |     at Function.handle (/hedgedoc/node_modules/express/lib/router/index.js:175:3)
app_1       |     at router (/hedgedoc/node_modules/express/lib/router/index.js:47:12)
app_1       | 2022-09-27T15:50:53.495Z info: 	172.21.0.1 - - [27/Sep/2022:15:50:53 +0000] "POST /new HTTP/1.1" 500 148 "-" "curl/7.82.0"

```

### Your Setup

- Host OS: Fedora 36
- NodeJS version: v16.14.0 (outside of docker though)
- HedgeDoc version: 1.9.4

**Comment by davidmehren** [comment]
The upcoming version 2 of HedgeDoc improves request validation and correctly responds with `400 Bad Request` and `Body Content-Type has to be text/markdown!`.

As this bug is fixed in HD2 and does not crash the app, I will close this according to our [maintenance policy](https://github.com/hedgedoc/hedgedoc#state-of-the-project).
