### ISSUE TITLE
uncaughtException: config.sslCAPath.forEach is not a function

### ISSUE THREAD

**Issue by sanzo-mlgb** [hedgedoc/hedgedoc#3369]
### Description

can't enable ssl

### Steps to reproduce

1. curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
2. apt install nodejs
3. npm install -g node-gyp yarn
4. wget https://github.com/hedgedoc/hedgedoc/releases/download/1.9.6/hedgedoc-1.9.6.tar.gz
5. tar -zxvf hedgedoc-1.9.6.tar.gz
6. mv hedgedoc /
7. chmod 777 -R /hedgedoc
8. cd /hedgedoc && ./bin/setup
9. edit config.json ( paste below )
10. NODE_ENV=production yarn start

### Expected behaviour

i can use https to access hedgedoc

### Logs

```shell
root@debian:/hedgedoc# NODE_ENV=production yarn start
yarn run v1.22.19
$ node app.js
2023-02-19T05:01:03.696Z error:         uncaughtException: config.sslCAPath.forEach is not a function
TypeError: config.sslCAPath.forEach is not a function
    at Object.<anonymous> (/hedgedoc/lib/config/index.js:186:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/hedgedoc/app.js:24:16)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
Done in 0.31s.
```

### Config

```shell
{
    "production": {
        "loglevel": "info",
        "db": {
            "dialect": "sqlite",
            "storage": "./db.hedgedoc.sqlite"
        },
        "allowOrigin": "192.168.238.139",
        "domain": "192.168.238.139",
        "useSSL": true,
        "protocolUseSSL": true,
        "sslCAPath": "./TLS/fullchain.cer",
        "sslCertPath": "./TLS/cert.cer",
        "sslKeyPath": "./TLS/key.key",
        "hsts": {
            "enable": true,
            "maxAgeSeconds": 31536000,
            "includeSubdomains": true,
            "preload": true
        },
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "true",
            "addDefaults": true,
            "allowPDFEmbed": false,
            "allowFraming": false
        },
        "cookiePolicy": "lax",
        "allowAnonymous": false,
        "allowAnonymousEdits": false,
        "allowFreeURL": false,
        "sessionSecret": "Fb40cmBXtv5v9H9mN19QItQ0ZhEkGcVqHFCv0Q0n4Lp9qzxIwWSrupvPWlpqziCi",
        "email": false,
        "allowEmailRegister": false,
        "urlAddPort": true
    }
}
```

### Your Setup

- Host OS: debian 11
- NodeJS version: v16.19.1
- HedgeDoc version: 1.9.6

### Additional context

if i remove this options,server works fine
        "useSSL": true,
        "protocolUseSSL": true,
        "sslCAPath": "./TLS/fullchain.cer",
        "sslCertPath": "./TLS/cert.cer",
        "sslKeyPath": "./TLS/key.key",
I think it is because the domain in the configuration is different from the domain name in the certificate?How do I configure it so that it can be accessed using domain names on the Internet and IP access on the intranet?

**Comment by mrdrogdrog** [comment]
It seems like you haven't configured sslCAPath correctly.
As you can see in the [docs](https://docs.hedgedoc.org/configuration/#hedgedoc-paths-stuff) this setting needs to be an array.
So the correct value would be `"sslCAPath": ["./TLS/fullchain.cer"]`

**Comment by sanzo-mlgb** [comment]
> It seems like you haven't configured sslCAPath correctly. As you can see in the [docs](https://docs.hedgedoc.org/configuration/#hedgedoc-paths-stuff) this setting needs to be an array. So the correct value would be `"sslCAPath": ["./TLS/fullchain.cer"]`

thank you for help, it works but get a new error :
`yarn run v1.22.19
$ node app.js
2023-02-19T07:42:26.471Z error:         uncaughtException: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)
    at tryReadSync (node:fs:438:20)
    at Object.readFileSync (node:fs:484:19)
    at Object.<anonymous> (/hedgedoc/app.js:50:17)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47`

**Comment by sanzo-mlgb** [comment]
> It seems like you haven't configured sslCAPath correctly. As you can see in the [docs](https://docs.hedgedoc.org/configuration/#hedgedoc-paths-stuff) this setting needs to be an array. So the correct value would be `"sslCAPath": ["./TLS/fullchain.cer"]`

think you for help ,it works but i get a new error
```
yarn run v1.22.19
$ node app.js
2023-02-19T07:42:26.471Z error:         uncaughtException: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:738:3)
    at tryReadSync (node:fs:438:20)
    at Object.readFileSync (node:fs:484:19)
    at Object.<anonymous> (/hedgedoc/app.js:50:17)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by mrdrogdrog** [comment]
Well the error message says it. The path you've provided doesn't point to a file but to a directory.

**Comment by davidmehren** [comment]
As there was no further reply in a month, I'm going to close this.
If you have further questions, you're welcome to join our community chat at chat.hedgedoc.org.
