### ISSUE TITLE
Unable to upgrade to 1.9.8 : webpack-cli failed

### ISSUE THREAD

**Issue by meepmeep** [hedgedoc/hedgedoc#4167]
### Description

Unable to run yarn build 

### Steps to reproduce

1. export NODE_ENV=production ; git pull ; ./bin/setup ; yarn install --production=false --frozen-lockfile ; yarn build

### Expected behaviour

Should update & install hedgedoc.

### Logs

```shell
Copying config files...
Installing packages...
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.55s.
If you want to build the frontend yourself, you need to run 'yarn install --frozen-lockfile' before 'yarn build' to install the devDependencies for the build process.

Edit the following config file to setup HedgeDoc server and client.
Read more info at https://docs.hedgedoc.org/configuration/

* config.json           -- HedgeDoc config
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > connect-session-sequelize@7.1.5" has incorrect peer dependency "sequelize@>= 6.1.0".
warning " > webpack-cli@5.1.3" has incorrect peer dependency "webpack@5.x.x".
warning "webpack-cli > @webpack-cli/configtest@2.1.1" has incorrect peer dependency "webpack@5.x.x".
warning "webpack-cli > @webpack-cli/info@2.0.2" has incorrect peer dependency "webpack@5.x.x".
warning "webpack-cli > @webpack-cli/serve@2.0.5" has incorrect peer dependency "webpack@5.x.x".
[5/5] Building fresh packages...
Done in 5.58s.
yarn run v1.22.19
$ webpack --config webpack.prod.js --progress
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'getArguments')
    at WebpackCLI.getBuiltInOptions (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/webpack-cli.js:831:77)
    at makeCommand.options.entry (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/webpack-cli.js:939:33)
    at async WebpackCLI.makeCommand (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/webpack-cli.js:443:31)
    at async loadCommandByName (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/webpack-cli.js:937:17)
    at async Command.<anonymous> (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/webpack-cli.js:1336:17)
    at async Command.parseAsync (/home/lufi/hedgedoc/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async WebpackCLI.run (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/webpack-cli.js:1360:9)
    at async runCLI (/home/lufi/hedgedoc/node_modules/webpack-cli/lib/bootstrap.js:9:9)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Your Setup

- Host OS: debian 11
- NodeJS version: v16.20.0
- HedgeDoc version: 19.7

### Additional context

I tried with yarn 3 : 

```
export NODE_ENV=production ; git pull ; ./bin/setup ; yarn install --production=false --frozen-lockfile ; yarn build
[...git stuff..]
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Copying config files...
Installing packages...
Unknown Syntax Error: Invalid option name ("--production=true").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
Unknown Syntax Error: Invalid option name ("--production=false").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
Internal Error: HedgeDoc@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/home/lufi/hedgedoc/.yarn/releases/yarn-3.6.0.cjs:435:5145)
    at kf.getCandidates (/home/lufi/hedgedoc/.yarn/releases/yarn-3.6.0.cjs:391:1264)
    at /home/lufi/hedgedoc/.yarn/releases/yarn-3.6.0.cjs:439:8033
    at df (/home/lufi/hedgedoc/.yarn/releases/yarn-3.6.0.cjs:390:11070)
    at ge (/home/lufi/hedgedoc/.yarn/releases/yarn-3.6.0.cjs:439:8013)

```

I think the issue comes from "warning "webpack-cli > @webpack-cli/configtest@2.1.1" has incorrect peer dependency "webpack@5.x.x".", but I don't know how to fix it ...

**Comment by mrdrogdrog** [comment]
The new release switched to yarn 3. Which has different CLI options
