### ISSUE TITLE
Cannot connect to mariadb 11.2.2 (Got an error writing communication packets)

### ISSUE THREAD

**Issue by cinimins** [hedgedoc/hedgedoc#5528]
### Description

I am using the official image `linuxserver/hedgedoc:version-1.9.0`. When trying to use a mariadb with `CMD_DB_URL=mariadb://user:pass@host:3306/hedgedoc`, I get a ton of these exceptions:

```
TypeError: this.throwError is not a function
    at Function.parseOkPacket (/opt/hedgedoc/node_modules/mariadb/lib/cmd/command.js:144:26)
    at Query.readOKPacket (/opt/hedgedoc/node_modules/mariadb/lib/cmd/resultset.js:141:30)
    at Query.readResponsePacket (/opt/hedgedoc/node_modules/mariadb/lib/cmd/resultset.js:40:21)
    at PacketInputStream.receivePacketBasic (/opt/hedgedoc/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
    at PacketInputStream.onData (/opt/hedgedoc/node_modules/mariadb/lib/io/packet-input-stream.js:169:20)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

The mariadb gives me the following error message every second:

```
2024-02-27 14:39:10 324 [Warning] Aborted connection 324 to db: 'hedgedoc' user: 'hedgedoc-user' host: 'w.x.y.z' (Got an error reading communication packets)
```

### Steps to reproduce

I am using the bitnami mariadb galera cluster with version 11.2.2 (Helm chart version 11.0.1) with default configurations.

### Expected behaviour

I would expect it to connect to the mariadb server.

### Your Setup

- Hedgedoc: `linuxserver/hedgedoc:version-1.9.0`
- Bitnami MariaDB Galera Helm-Chart: Version `11.0.1`

**Comment by ErikMichelson** [comment]
> I am using the official image `linuxserver/hedgedoc:version-1.9.0`.

The linuxserver image is community-contributed and not official. Have you tried the same setup using the [official images](https://docs.hedgedoc.org/setup/docker/) with the latest version (1.9.9 at the time of writing this comment)?

> I am using the bitnami mariadb galera cluster with version 11.2.2

I'm not sure about how different MariaDB cluster works from standalone MariaDB deployments. When the same error occurs with the official image, could you please report it back for further investigation? Thanks.

**Comment by cinimins** [comment]
Thank you @ErikMichelson! I wasn't aware that there was an official Docker image. I must have taken that image from the unofficial Helm chart and assume it was the only available docker image.

It works with the actual official image now, thank you!
