### ISSUE TITLE
OAuth login with Nextcloud broken after 1.7.0 upgrade

### ISSUE THREAD

**Issue by vberger** [hedgedoc/hedgedoc#608]
**Description**

After update to 1.7.0-rc1 from 1.6.0, when trying to login using Oauth2 with Nextcloud as a provider, the processing of the return callback (`/auth/oauth2/callback?...`) causes Hedgedoc to crash.

**To Reproduce**

Upgrade was done following the instructions at https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/manual-setup.md#how-to-upgrade-your-installation

Then, on login:

- On the main page, click "sign-in"
- On the popup, choose "sign in via Oauth2"
- Redirection to Nextcloud occurs, authorize the login
- Observe the "502 Bad Gateway" page from nginx (due to hedgedoc having crashed)

**Expected behavior**

The user is logged in and Hedgedoc does not crash

**Logs**

Nginx logs:
```
2020/11/30 11:13:44 [error] 19841#19841:
    *4962140 upstream prematurely closed connection while reading response header from upstream,
    client: <redacted>, server: <redacted>,
    request: "GET /auth/oauth2/callback?state=<redacted>&code=<redacted> HTTP/1.1",
    upstream: "http://unix:///run/hedgedoc/hedgedoc.sock:/auth/oauth2/callback?state=<redacted>&code=<redacted>",
    host: "<redacted>"
```

Hedgedoc logs:
```
2020-11-30T11:08:06.089Z error: 	uncaughtException: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at extractProfileAttribute (/opt/hedgedoc/lib/web/auth/oauth2/index.js:46:15)
    at checkAuthorization (/opt/hedgedoc/lib/web/auth/oauth2/index.js:69:17)
    at /opt/hedgedoc/lib/web/auth/oauth2/index.js:99:5
    at passBackControl (/opt/hedgedoc/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/opt/hedgedoc/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020-11-30T11:08:06.090Z error: 	An uncaught exception has occured.
2020-11-30T11:08:06.090Z error: 	Cannot read property 'split' of undefined
2020-11-30T11:08:06.090Z error: 	Process will exit now.
```

**Config**

Oauth2 config of Hedgedoc

```
"oauth2": {
    "clientID": "<redacted>",
    "clientSecret": "<redacted>",
    "authorizationURL": "https://<nextcloud host>/apps/oauth2/authorize",
    "tokenURL": "https://<nextcloud host>/apps/oauth2/api/v1/token",
    "userProfileURL": "https://<nextcloud host>/ocs/v2.php/cloud/user?format=json",
    "userProfileUsernameAttr": "ocs.data.id",
    "userProfileDisplayNameAttr": "ocs.data.display-name",
    "userProfileEmailAttr": "ocs.data.email"
}
```

**Your Setup (please complete the following information):**
 - Host OS: Debian 10.6
 - NodeJS version: v10.21.0
 - HedgeDoc version: 1.7.0-rc1

**Additional context**

Not sure what to add, but I can try a few things if needed.

**Comment by davidmehren** [comment]
Thanks for testing and reporting!

I just tried OAuth with a quick Nextcloud Docker container and yep, it crashes :D
The culprit seems to be the new OAuth authorization logic, which doesn't handle the case of no `config.oauth2.rolesClaim` being set.

I'll have a fix ready shortly.

**Comment by davidmehren** [comment]
@vberger Could you try if the fix in #609 works four you?

**Comment by vberger** [comment]
Yes, it works with this fix. :+1:

**Comment by pabsta1** [comment]
Hi, I am getting the a similar problem, although not related to an upgrade. The symptoms are identical, although the Hedgedoc logs are different. The generic description is exactly the same (hedgedoc passes the request to nextcloud, which authorizes the request, and hedgedoc crashes upon receiving the url.). The expected behaviour, of course is to have users logged in. Here are the logs: 

**Nginx:**

`2021/07/18 01:48:03 [error] 27178#27178: *159 upstream prematurely closed connection while reading response header from upstream, client: XXX, server: XXX, request: "GET /auth/oauth2/callback?state=XXX&code=XXX HTTP/2.0", upstream: "https://127.0.0.1:3000/auth/oauth2/callback?state=XXX&code=XXX", host: "XXX"
`

**Hedgedoc**
```

2021-07-18T01:48:03.207Z error: 	uncaughtException: The "url" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at Url.parse (node:url:169:3)
    at Object.urlParse [as parse] (node:url:156:13)
    at exports.OAuth2._request (/var/www/hedgedoc/node_modules/oauth/lib/oauth2.js:72:22)
    at exports.OAuth2.get (/var/www/hedgedoc/node_modules/oauth/lib/oauth2.js:227:8)
    at OAuth2CustomStrategy.userProfile (/var/www/hedgedoc/lib/web/auth/oauth2/index.js:93:16)
    at loadIt (/var/www/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:374:17)
    at OAuth2CustomStrategy.OAuth2Strategy._loadUserProfile (/var/www/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:389:25)
    at /var/www/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:177:16
    at /var/www/hedgedoc/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/var/www/hedgedoc/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/var/www/hedgedoc/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2021-07-18T01:48:03.207Z error: 	An uncaught exception has occured.
2021-07-18T01:48:03.207Z error: 	The "url" argument must be of type string. Received undefined
2021-07-18T01:48:03.207Z error: 	Process will exit now.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**oauth2 config:**

"oauth2": {
                "clientID": "XXX",
                "clientSecret" : "XXX",
                "authorizationURL": "https://XXX/index.php/apps/oauth2/authorize",
                "tokenURL" :        "https://XXX/index.php/apps/oauth2/api/v1/tok$
                "userProfileUrl" :  "https://XXX/ocs/v2.php/cloud/user?format=jso$
                "userProfileUsernameAttr" : "ocs.data.id",
                "userProfileDisplayNameAttr" : "ocs.data.display-name",
                "userProfileEmailAttr" : "ocs.data.email"
        }

**General config info:**

Server: Debian Buster. 
Hedgedoc: latest (as of yesterday). 
NPM: 7.20.0

Happy to provide additional information if needed.  Any help would be usefull.

**Comment by pabsta1** [comment]
Edit: David, a moderator on [Matrix](https://matrix.to/#/#hedgedoc:matrix.org?via=matrix.org&via=kif.rocks&via=tchncs.de), aptly suggested changing the tag `userProfileUrl` for `userProfileURL`, which solved the problem.

**Comment by ccoenen** [comment]
we could actually throw an error right here:

https://github.com/hedgedoc/hedgedoc/blob/8d8ec241081b3f0185dc4a68b97a88e6f9df8c44/lib/web/auth/oauth2/index.js#L17

At this point it would already be clear that OAuth2 is being used _and_ that it will fail without a valid URL. (yes, it might fail with a syntactically correct, yet not-working URL later, too). This would catch the configuration error early.
