### ISSUE TITLE
Using the release tarball and not building the frontend results in errors

### ISSUE THREAD

**Issue by aptalca** [hedgedoc/hedgedoc#639]
**Description**
Using the release tarball and following the [instructions](https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/manual-setup.md#instructions) to install. It starts fine, but when I try to access the webpage, I get "Internal Server Error" in the browser (log message below)

**To Reproduce**
Download the release tarball: https://github.com/hedgedoc/hedgedoc/releases/download/1.7.0/hedgedoc-1.7.0.tar.gz
Follow the steps from https://github.com/hedgedoc/hedgedoc/blob/master/docs/setup/manual-setup.md#instructions
Skip building the frontend
Start with npm

Alternatively, if I build the frontend with `npm run build`, everything works fine (but takes forever to build).

**Expected behavior**
Expect the gui to come up

**Logs**
```
Sequelize CLI [Node: 12.20.0, CLI: 5.5.1, ORM: 5.22.3]

Loaded configuration file "../../config/config.json".
No migrations were executed, database schema was already up to date.
2020-12-22T20:22:05.992Z warn:  Neither 'domain' nor 'CMD_DOMAIN' is configured. This can cause issues with various components.
Hint: Make sure 'protocolUseSSL' and 'urlAddPort' or 'CMD_PROTOCOL_USESSL' and 'CMD_URL_ADDPORT' are configured properly.
2020-12-22T20:22:05.994Z warn:  Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
2020-12-22T20:22:06.702Z info:  HTTP Server listening at 0.0.0.0:3000
Error: Could not find the include file "../build/cover-header"
    at getIncludePath (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:165:13)
    at includeSource (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:309:17)
    at /opt/hedgedoc/node_modules/ejs/lib/ejs.js:745:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:721:15)
    at includeSource (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:313:9)
    at /opt/hedgedoc/node_modules/ejs/lib/ejs.js:745:26
    at Array.forEach (<anonymous>)
    at Template.generateSource (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:721:15)
    at Template.compile (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:574:12)
    at Object.compile (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:392:16)
    at handleCache (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:215:18)
    at tryHandleCache (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:254:16)
    at View.exports.renderFile [as engine] (/opt/hedgedoc/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/opt/hedgedoc/node_modules/express/lib/view.js:135:8)
    at tryRender (/opt/hedgedoc/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/hedgedoc/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/hedgedoc/node_modules/express/lib/response.js:1012:7)
    at showIndex (/opt/hedgedoc/lib/response.js:47:9)
    at Layer.handle [as handle_request] (/opt/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/hedgedoc/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/hedgedoc/node_modules/express/lib/router/route.js:112:3)
2020-12-22T20:22:35.639Z info:  192.168.13.58 - - [22/Dec/2020:20:22:35 +0000] "GET / HTTP/1.1" 500 148 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```

**Config**
Using linuxserver docker image (I'm one of the team members)

**Your Setup (please complete the following information):**
 - Host OS: Ubuntu 18.04 (docker image also using bionic)
 - NodeJS version: 12
 - HedgeDoc version: 1.7.0

**Comment by davidmehren** [comment]
I'm a bit confused, what do you mean by "Using linuxserver docker image"?
How do you combine the manual setup with the docker image?

The release tarball does contain `/hedgedoc/public/views/build/cover-header.ejs` and other instances work fine with it.

**Comment by aptalca** [comment]
I'm one of the linuxserver developers. I'm essentially, removing [this line](https://github.com/linuxserver/docker-hedgedoc/blob/initial/Dockerfile#L49) and pulling the release tarball instead of the git tarball, on a local build.

**Comment by aptalca** [comment]
I'll commit what I have and we can see the jenkins build and the test results

**Comment by aptalca** [comment]
Welp, this is embarrassing. It seems I mixed and matched my dockerfiles. I retraced my steps and all is working well.

Btw, I'm loving the fact that the frontend is included in the release tarball. It used to take over an hour to build the docker image, and would often kill our arm builders so we had to build all arches with qemu on x86_64. Now we can build much faster and on native hardware.
