### ISSUE TITLE
Upload images issue

### ISSUE THREAD

**Issue by NBALLAND** [hedgedoc/hedgedoc#697]
Hello,

I'm facing an issue with pictures uploads.

The image is uploaded in public/uploads but it doesn't appear in the note

I just get "![Uploading file..._gsemmn16z]()" on the note and it is stucked on this.

If I type ![](/uploads/upload_3bd93d05ff0a76ce432c8c1e7507bfdd.jpg) _[upload_3bd93d05ff0a76ce432c8c1e7507bfdd.jpg is the imag I've jsut uploaded], the image is displayed.

Below the log:

Thank you for your help

2021-01-08T12021-01-08T14:23:50.005Z debug:     new operation: {"wrapped":[178,"![Uploading file..._ww1e3ne25]()\n",2],"meta":{"ranges":[{"anchor":211,"head":211}]}}
2021-01-08T14:23:50.079Z info:  Executing (default): SELECT `sid`, `expires`, `data`, `createdAt`, `updatedAt` FROM `Session` AS `Session` WHERE `Session`.`sid` = '1mqE-qIubyBovrluDOAmk_d3xPNAJ1sh';
2021-01-08T14:23:50.085Z info:  Executing (default): SELECT `id`, `profileid`, `profile`, `history`, `accessToken`, `refreshToken`, `deleteToken`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`id` = 'bf31a7c8-3888-44eb-850b-0747124d4c60';
2021-01-08T14:23:50.089Z info:  deserializeUser: bf31a7c8-3888-44eb-850b-0747124d4c60
2021-01-08T14:23:50.105Z debug:         SERVER received uploadimage: {"size":12357,"path":"/tmp/hedgedoc-Ud5Hkv/upload_8e2e5d3694337886c9774cc03d5a77f3.png","name":"image-1610115829261.png","type":"image/png","mtime":"2021-01-08T14:23:50.098Z"}
2021-01-08T14:23:50.106Z debug:         imageRouter: Uploading /tmp/hedgedoc-Ud5Hkv/upload_8e2e5d3694337886c9774cc03d5a77f3.png using filesystem
(node:7365) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
    at onParseError (internal/url.js:241:9)
    at new URL (internal/url.js:317:5)
    at new URL (internal/url.js:314:22)
    at Object.exports.uploadImage (/var/www/html/hedgedoc/lib/web/imageRouter/filesystem.js:28:19)
    at /var/www/html/hedgedoc/lib/web/imageRouter/index.js:63:22
(node:7365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
2021-01-08T14:23:50.986Z debug:         updater found dirty note: aac44714-6d6d-478b-849e-1d365a2bc267
2021-01-08T14:23:50.989Z info:  Executing (default): SELECT `id`, `shortid`, `alias`, `permission`, `viewcount`, `title`, `content`, `authorship`, `lastchangeAt`, `savedAt`, `createdAt`, `updatedAt`, `ownerId`, `lastchangeuserId` FROM `Notes` AS `Note` WHERE `Note`.`id` = 'aac44714-6d6d-478b-849e-1d365a2bc267';
2021-01-08T14:23:51.006Z info:  Executing (default): SELECT `id`, `profileid`, `profile`, `history`, `accessToken`, `refreshToken`, `deleteToken`, `email`, `password`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE `User`.`id` = 'bf31a7c8-3888-44eb-850b-0747124d4c60';
2021-01-08T14:23:51.011Z info:  Executing (default): UPDATE `Notes` SET `content`=?,`authorship`=?,`lastchangeAt`=?,`updatedAt`=? WHERE `id` = ?
2021-01-08T14:23:51.012Z debug:         read history success: bf31a7c8-3888-44eb-850b-0747124d4c60
2021-01-08T14:23:51.026Z info:  Executing (default): UPDATE `Users` SET `history`=?,`updatedAt`=? WHERE `id` = ?
2021-01-08T14:23:55.428Z info:  Executing (default): SELECT `id`, `shortid`, `alias`, `permission`, `viewcount`, `title`, `content`, `authorship`, `lastchangeAt`, `savedAt`, `createdAt`, `updatedAt`, `ownerId`, `lastchangeuserId` FROM `Notes` AS `Note` WHERE ((`Note`.`lastchangeAt` IS NULL OR (`Note`.`lastchangeAt` IS NOT NULL AND `Note`.`lastchangeAt` > `createdAt`)) AND (`Note`.`savedAt` IS NULL OR `Note`.`savedAt` < `lastchangeAt`));
2021-01-08T14:23:55.436Z info:  Executing (default): SELECT `id`, `patch`, `lastContent`, `content`, `length`, `authorship`, `createdAt`, `updatedAt`, `noteId` FROM `Revisions` AS `Revision` WHERE `Revision`.`noteId` = 'aac44714-6d6d-478b-849e-1d365a2bc267' ORDER BY `Revision`.`createdAt` DESC;
2021-01-08T14:23:55.463Z info:  Executing (default): INSERT INTO `Revisions` (`id`,`patch`,`content`,`length`,`authorship`,`createdAt`,`updatedAt`,`noteId`) VALUES (?,?,?,?,?,?,?,?);
2021-01-08T14:23:55.546Z info:  Executing (default): UPDATE `Revisions` SET `content`=?,`updatedAt`=? WHERE `id` = ?
2021-01-08T14:23:55.608Z info:  Executing (default): UPDATE `Notes` SET `savedAt`=?,`updatedAt`=? WHERE `id` = ?

**Comment by NBALLAND** [comment]
Precision, I'm connected to the server through a VPN if it helps...

**Comment by SISheogorath** [comment]
You have to set the domain setting. Please check this community forum entry:

https://community.hedgedoc.org/t/filesystem-uploads-in-codimd-container/94/
